server:
  port: 9000
spring:
  application:
    name: hello-consumer-ribbon
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/